<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Amit" failures="0" tests="5" name="com.api.runner.TestRunner" time="5.783" errors="1" timestamp="2025-01-23T20:02:24 IST" skipped="0">
  <testcase classname="com.api.runner.TestRunner" name="runScenario" time="0.199"/>
  <system-out/>
  <testcase classname="com.api.runner.TestRunner" name="runScenario" time="0.266"/>
  <system-out/>
  <testcase classname="com.api.runner.TestRunner" name="runScenario" time="0.207"/>
  <system-out/>
  <testcase classname="com.api.runner.TestRunner" name="runScenario" time="0.194"/>
  <system-out/>
  <testcase classname="com.api.runner.TestRunner" name="runScenario" time="4.917">
    <error message="Cannot invoke &quot;io.restassured.response.Response.getStatusCode()&quot; because &quot;this.response&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.response.Response.getStatusCode()" because "this.response" is null
at com.api.stepdefinition.GetUserStep.the_api_call_got_success_with_status_code(GetUserStep.java:37)
at âœ½.the api call got success with "201" status code(file:///C:/Users/amitp/Learning/Rest_Assued_Framework/src/test/java/com/api/Features/CreateUser.feature:6)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- com.api.runner.TestRunner -->
